name: eval_front
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  flutter_highlight: ^0.7.0
  flutter_code_editor: ^0.2.7
  # 또는
  code_text_field: ^1.0.2
  cupertino_icons: ^1.0.2

  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/

